### ISSUE TITLE
mt.PrettyString() panics for even slightly longer number of leaf nodes

### ISSUE THREAD

**Issue by grempe** [lynn9388/merkletree#1]
The following code sample demonstrates a `panic` that occurs if the length of the leaf nodes is `>= 7` in length. This sample is identical to your README sample, except I've increased the length of the `test` slice.

The line of source in the Go repo that panics is (note slightly different line num here than in my report. I'm pointing at the same place in this link.):

https://github.com/golang/go/blob/master/src/strings/strings.go#L532

Any suggestions?

```go
package main

import (
	"fmt"

	"github.com/lynn9388/merkletree"
)

func main() {
	// original sample : Works!
	// tests := [][]byte{[]byte("http"), []byte("www"), []byte("lynn"), []byte("9388"), []byte("com")}
	// slightly longer sample : Panics!
	tests := [][]byte{[]byte("http"), []byte("www"), []byte("lynn"), []byte("9388"), []byte("com"), []byte("will"), []byte("panic")}
	mt := merkletree.NewMerkleTree(tests...)

	fmt.Println("Merkle Tree:\n" + mt.PrettyString(6, 2))
}

// PANIC OUTPUT:
////////////////

// $ go run main.go
// panic: strings: negative Repeat count

// goroutine 1 [running]:
// strings.Repeat(0x10cb800, 0x1, 0xfffffffffffffff9, 0xc000016890, 0x9)
// 	/usr/local/opt/go/libexec/src/strings/strings.go:543 +0x1ec
// github.com/lynn9388/merkletree.(*MerkleTree).PrettyString(0xc00000c048, 0x6, 0x2, 0xc00000c048, 0x5)
// 	/Users/glenn/.go/src/github.com/lynn9388/merkletree/merkletree.go:228 +0xecf
// main.main()
// 	/tmp/mt/main.go:16 +0x3a8
// exit status 2
```

**Comment by lynn9388** [comment]
The code has been refactored and more tests have been added. The new [example code](https://play.golang.org/p/8sX5M09ahKa) works fine

```go
package main

import (
	"fmt"

	"github.com/lynn9388/merkletree/binary"
)

func main() {
	mt := binary.New([]byte("http"), []byte("www"), []byte("lynn"), []byte("9388"), []byte("com"), []byte("will"), []byte("panic"))

	fmt.Println("Merkle Tree:\n" + mt.PrettyString(6))
}
```

Result

```
Merkle Tree:
                                c42bc2
                                 / \
                                /   \
                               /     \
                              /       \
                             /         \
                            /           \
                           /             \
                          /               \
                         /                 \
                        /                   \
                       /                     \
                      /                       \
                     /                         \
                    /                           \
                   /                             \
                  /                               \
                 /                                 \
              1b5c1e                             e34f76
               / \                                 / \
              /   \                               /   \
             /     \                             /     \
            /       \                           /       \
           /         \                       3b0b2d   79631c
          /           \                       / \
         /             \                     /   \
        /               \                   /     \
     4b2099           19ec96               /       \
      / \               / \             71b4f3   bc16f5
     /   \             /   \
    /     \           /     \
   /       \         /       \
e0603c   7c2ecd   1502fe   6d86b7
```
